### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by JoseCarlosGarcia** [JavierMarrero/jlibgraph#73]
Al inicio de un algoritmo duplico el grafo para poder eliminar nodos y aristas y obtener el resultado deseado sin variar el grafo original. Durante la ejecución del algoritmo elimino un nodo del grafo clonado y luego al llamar a un nuevo iterardor para el grafo clonado, me encuentro que sí se eliminan los nodos pero cuando accedo a uno de los nodos aun presente en el grafo y veo sus aristas que llegan o salen encuentro algunas de las aristas que lo conectaban con los nodos que se eliminaron.

En la siguiente imagen se muestra un caso, en la variable **conectionsToVertex** se encuentra una arista 2-> 4 sin embargo, el nodo 2 fue eliminado anteriormente.
 
![image](https://user-images.githubusercontent.com/117756480/202869902-20796fff-d654-450e-9a5e-ca808ccad13b.png)

En la imagen que se encuentra a continuación encontré lo siguiente:
Al eliminar un nodo del grafo clonado encontró que tenía tres aristas hacia él, entró al for de eliminar estas aristas 3 veces pero dos de ellas no las eliminó y se quedan a pesar de haber eliminado el vértice después.

![image](https://user-images.githubusercontent.com/117756480/202869576-802a938d-b3f5-49ba-b36d-9f8a700d2fdb.png)

Tener en cuenta también:
- Al crear un copia del grafo en el método duplicate() se le pasa por parámetro al constructor del grafo que la copia será un grafo dirigido.
- Se ejecutó el algoritmo utilizando el grafo original y sí funcionaba

**Comment by JavierMarrero** [comment]
Evidentemente el error está en la clonación del grafo. Quizás las aristas no se incorporan bien a los `HashSet` que deben contenerlas, o se incorporan dobles, aunque los sets no deben tener tener duplicados (lo cual puede ser indicador de que el método `equals` no está funcionando bien para las aristas).

**Comment by JavierMarrero** [comment]
Revisaré los métodos de clonación y trabajaré de nuevo el método `equals `de las aristas. 👍🏼

**Comment by JavierMarrero** [comment]
Me gustaría llamar la atención de @cdrobaina01 al problema, en caso de que encuentre modo de solucionar el bug.

**Comment by JavierMarrero** [comment]
@JoseCarlosGarcia gracias por reportar el issue 😀

**Comment by JavierMarrero** [comment]
Me gustaría llamar la atención sobre el resto de colaboradores: @SnowBlackQueen, @Amy-Mendez, que estén al tanto y cualquier otro bug que encuentren en el código sea reportado como issue en forma similar a como fue este, con vistas a la liberación de la versión 1.0.

**Comment by JavierMarrero** [comment]
Ya el bug fue cerrado con el commit #80
